### ISSUE TITLE
Windows support (readline stdlib)

### ISSUE THREAD

**Issue by maread99** [beancount/beanquery#109]
Hi

I notice that `beanquery` is [using](https://github.com/beancount/beanquery/blob/ca24621e377130fa4763812c0b8ebb8c62ebb9b0/beanquery/shell.py#L11) the `readline` stdlib. This library is (I believe) not available to Python Window's installations. Is the lack of support for Windows intentional?

**Comment by dnicolodi** [comment]
It is not intentional. It is an oversight mostly due to the fact that `readline` is available on the platforms where I use `beanquery` and to my wrong impression that readline is a thing on Windows too these days. I am surprised that the tests run on Windows didn't catch this. The test coverage of the interactive shell is minimal, but I thought that there at least a minimal smoke tests.

**Comment by dnicolodi** [comment]
The CI runs only on Linux, that's why it didn't catch the missing dependency.

**Comment by maread99** [comment]
Thanks for looking at this @dnicolodi.
