### ISSUE TITLE
Badges for README.md

### ISSUE THREAD

**Issue by WolfgangFahl** [beancount/beanquery#209]
# beanquery

Customizable lightweight SQL query tool

[![GitHub issues](https://img.shields.io/github/issues/beancount/beanquery.svg)](https://github.com/beancount/beanquery/issues)
[![GitHub closed issues](https://img.shields.io/github/issues-closed/beancount/beanquery.svg)](https://github.com/beancount/beanquery/issues/?q=is%3Aissue+is%3Aclosed)
[![pypi](https://img.shields.io/pypi/pyversions/beanquery)](https://pypi.org/project/beanquery/)
[![PyPI Status](https://img.shields.io/pypi/v/beanquery.svg)](https://pypi.python.org/pypi/beanquery/)
[![Documentation](https://img.shields.io/badge/docs-beancount-blue)](https://beancount.github.io/docs/beancount_query_language.html)
[![License](https://img.shields.io/github/license/beancount/beanquery.svg)](https://github.com/beancount/beanquery/blob/main/LICENSE)

beanquery is a customizable and extensible lightweight SQL query tool that works on tabular data, including [Beancount](https://beancount.github.io/) ledger data.

**Comment by WolfgangFahl** [comment]
cut&paste to a README.md of the above github markup should work out of the box.

**Comment by dnicolodi** [comment]
I don't like the concept of badges. Most likely because I'm not much into this kind of vanity. These specific badges in particular are not useful.

The number of open and closed issues is completely irrelevant to all users, if someone is curious enough, the number is readily available on GitHub. The Python compatibility information is apparently taken from the package trove classifiers of the package published on PyPI. The classifiers are displayed on the PyPI page already. However, the README is also visible on the GitHub landing page for the project. There the badge already shows outdated information. I don't understand what's the point of showing the latest release on PyPI in the README. When it is shown on PyPI, the same information is available more prominently on the same page. It could have some minimal value when shown on GitHub. The documentation link points to outdated documentation. Patches that improve the documentation are more than welcome. The license is already prominently displayed on GitHub and PyPI.

Finally, beanquery's README is not in Markdown format.
